# Configuration for Phase 2 Benchmarking (run_benchmark_manual.py)

# Add for reproducibility
random_seed: 42

# Models to test: key -> {provider: str, api_id: str, context_window: int}
models_to_test:
  gpt-4o-mini:  { provider: openai, api_id: gpt-4o-mini,          context_window: 128000 }
#  gemini-1.5p:  { provider: google, api_id: models/gemini-1.5-pro-latest, context_window: 1000000 }
  llama3-3.3-70b-versatile: { provider: groq, api_id: llama-3.3-70b-versatile, context_window: 128000 }
#  mixtral-large: { provider: groq, api_id: mixtral-8x7b-32768,      context_window: 32768 }
  deepseek-70b:     {provider: groq,  api_id: deepseek-r1-distill-llama-70b, context_window: 128000}
#  llama3-8b-local: { provider: ollama, api_id: llama3:8b, base_url: "http://localhost:11434", context_window: 8192 }

# Define retrievers and prompts to test
# retrievers_to_test: ["none", "hybrid"]
retrievers_to_test: ["none", "bm25", "dense"]
prompts_to_test: ["zero_shot", "few_shot_cot"]
# prompts_to_test: ["zero_shot", "few_shot", "few_shot_cot"]

# Embedding models
dense_retriever_embedder: "BAAI/bge-large-en-v1.5"
semantic_similarity_embedder: "sentence-transformers/all-MiniLM-L6-v2" # For analysis script

# Retrieval parameters
retrieval_params:
  # Chunking
  chunk_size_tokens: 512
  chunk_overlap_tokens: 64
  # Retrieval K values
  bm25_k: 10
  dense_k: 10
  hybrid_k: 10
  # Hybrid MMR
  mmr_lambda: 0.5
  # Indexing
  pyserini_threads: 4
  embedding_batch_size: 32
  force_reindex: false # Set to true to rebuild indices on next run
  # Prompting / Context
  context_buffer_tokens: 500 # Tokens reserved for prompt/response
  num_few_shot_examples: 3
  few_shot_strategy: 'stratified' # 'stratified' or 'random'
  llm_response_buffer_tokens: 4096 # Buffer for LLM response generation

# Scoring parameters (Used by analysis script, not this one)
scoring_params:
  sem_em_threshold: 0.90
  page_acc_tolerance: 1

# API parameters
api_params:
  api_delay_seconds: 0.2
  api_max_retries: 3    # Max retries for transient errors (e.g., rate limits)
  api_retry_delay: 3   # Seconds to wait between retries

files:
  # Path relative to the main project directory
  system_prompt: "system_instructions.md"